name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build solutions/dotnet/.devcontainer/Dockerfile
    - name: Run tests
      run: docker run -it dotnet test **/*.Tests.csproj
