name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t local < solutions/dotnet/.devcontainer/Dockerfile
    - name: Run tests
      run: docker run -it -v dotnet test **/*.Tests.csproj
