name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    types: [opened, synchronize, reopened]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.4.0
    - name: dotnet-sonarscanner
      uses: Secbyte/dotnet-sonarscanner@v2.2
      with:
        # Command to invoke build
        buildCommand: 'dotnet build **/*.csproj'
        # Command to invoke tests
        testCommand: 'dotnet test **/*.Tests.csproj'
        # Specifies the key of the analyzed project in SonarQube
        projectKey: wulfland_CodingDojo
        # Specifies the name of the analyzed project in SonarQube
        projectName: CodingDojo
        # Organisation
        sonarOrganisation: wulfland-github
        # Arguments to append to the begin command
        beginArguments: >
          /d:sonar.verbose="true"
          /d:sonar.cs.opencover.reportsPaths='"/path/to/coverage.xml","/path/to/coverage.2.xml"'
          /d:sonar.coverage.exclusions='"**/*.cs","**/*.md"'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      
